# Generated by Django 3.1.4 on 2023-01-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='session_key',
            new_name='session',
        ),
    ]
